spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/blog_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.config.import=optional:classpath:application-local.properties

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.private-key-path=classpath:keys/private.pem
jwt.public-key-path=classpath:keys/public.pem
jwt.expiration=900000

# 900000 ms = 15 min (access token)